In [1]:
import sqlite3
import pandas as pd

C:\Users\hp\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.gk7gx5keq4f6uyo3p26ulgbqyhgqo7j4.gfortran-win_amd64.dll
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
data = pd.read_excel(r"C:\Users\hp\Downloads\Prime\.ipynb_checkpoints\ecommerce-sales-business-analytics\data\newdata.xlsx")

In [3]:
data.head(5)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name.1,Unit Price,quantity,discount,shipping_cost,order_priority,sales,expenses,revenue,year
0,AG-2011-2040,2011-01-01,2011-01-06,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Blue,211,2,0.0,35.46,Medium,422,397.9902,457.46,2011
1,IN-2011-47883,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,High Speed,129,3,0.1,9.72,Medium,387,311.4774,358.02,2011
2,HU-2011-1220,2011-01-01,2011-01-05,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Single Width,128,4,0.0,8.17,High,512,452.5479,520.17,2011
3,IT-2011-3647632,2011-01-01,2011-01-05,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Premium,177,3,0.5,4.82,High,531,235.1784,270.32,2011
4,CA-2011-1510,2011-01-01,2011-01-08,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Duo Pack,222,5,0.1,4.70,Medium,1110,873.2190,1003.70,2088

In [4]:
data.shape

(51318, 24)

# create database

In [5]:
ecommerce_database = sqlite3.connect(r"C:\Users\hp\Downloads\Prime\.ipynb_checkpoints\ecommerce-sales-business-analytics\data\ecommerce.db")

In [6]:
data.to_sql(
    "ecommerce",
    ecommerce_database,
    if_exists="replace",
    index=False
)

51318

In [7]:
query = """
SELECT *
FROM ecommerce
LIMIT 10;
"""

result = pd.read_sql_query(query, ecommerce_database)

result

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name.1,Unit Price,quantity,discount,shipping_cost,order_priority,sales,expenses,revenue,year
0,AG-2011-2040,2011-01-01 00:00:00,2011-01-06 00:00:00,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Blue,211,2,0.0,35.46,Medium,422,397.9902,457.46,2011
1,IN-2011-47883,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,High Speed,129,3,0.1,9.72,Medium,387,311.4774,358.02,2011
2,HU-2011-1220,2011-01-01 00:00:00,2011-01-05 00:00:00,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Single Width,128,4,0.0,8.17,High,512,452.5479,520.17,2011
3,IT-2011-3647632,2011-01-01 00:00:00,2011-01-05 00:00:00,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Premium,177,3,0.5,4.82,High,531,235.1784,270.32,2011
4,CA-2011-1510,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Duo Pack,222,5,0.1,4.70,Medium,1110,873.2190,1003.70,2088
5,IN-2011-79397,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,8.5 x 11,299,2,0.1,1.80,Medium,598,469.8000,540.00,2011
6,ID-2011-80230,2011-01-02 00:00:00,2011-01-06 00:00:00,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,...,Wireless,378,1,0.0,24.10,Medium,378,349.8270,402.10,2011
7,IZ-2011-4680,2011-01-03 00:00:00,2011-01-03 00:00:00,Same Day,Kean Nguyen,Corporate,New South Wales,Australia,APAC,Oceania,...,White,254,1,0.1,125.32,Critical,254,307.9104,353.92,2011
8,IN-2011-65159,2011-01-03 00:00:00,2011-01-09 00:00:00,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Laser,400,4,0.4,107.10,Low,1600,928.3770,1067.10,2011
9,ES-2011-4869686,2011-01-03 00:00:00,2011-01-07 00:00:00,Standard Class,Lindsay Williams,Corporate,Ninawa,Iraq,EMEA,EMEA,...,Set of Two,60,4,0.0,81.26,High,240,279.4962,321.26,2001

In [8]:
# Total sales
query = """select sum(sales) as total_sales
from ecommerce;
"""

pd.read_sql_query(query,ecommerce_database)

   total_sales
0     42397613

In [9]:
# Sales by category
query = """select category, sum(sales) as total_sales
            from ecommerce
            group by category
            order by total_sales desc;
            """
pd.read_sql_query(query, ecommerce_database)

          category  total_sales
0  OFFICE SUPPLIES     25721061
1       TECHNOLOGY      8381770
2        FURNITURE      8294782

In [10]:
# Top 10 products
query = """select product_name, sum(sales) as total_sales
            from ecommerce
            group by product_name
            order by total_sales desc
            limit 10;"""
pd.read_sql_query(query,ecommerce_database)

               product_name  total_sales
0                   Staples       197034
1        Acco Binder Covers       149775
2  Sanford Pencil Sharpener       140023
3         Acco 3-Hole Punch       138994
4       Avery Binder Covers       138361
5        Cardinal Index Tab       137328
6         Stockwell Staples       137136
7     Avery Binding Machine       137125
8    Wilson Jones Index Tab       137004
9       Stockwell Push Pins       132942

# 1. Dataset overview

In [11]:
# Q1 — Total number of rows
query = """select count(*) as total_no_rows
            from ecommerce;"""
pd.read_sql_query(query, ecommerce_database)

   total_no_rows
0          51318

In [12]:
# Q2 — Number of unique orders
query = """select count(distinct order_id) as unique_orders
            from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   unique_orders
0          25035

In [13]:
# Q3 — Number of unique customers
query = """select count(distinct customer_name) as unique_customers
            from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   unique_customers
0               795

In [14]:
# Q4 — Number of unique products
query = """select count(distinct product_name) as unique_products
            from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   unique_products
0             2287


# 2. Basic numerical analysis

In [15]:
# Inspect the columns of the ecommerce table
columns_df = pd.read_sql_query("PRAGMA table_info(ecommerce);", ecommerce_database)
print(columns_df[['name', 'type']])

              name       type
0         order_id       TEXT
1       order_date  TIMESTAMP
2        ship_date  TIMESTAMP
3        ship_mode       TEXT
4    customer_name       TEXT
5          segment       TEXT
6            state       TEXT
7          country       TEXT
8           market       TEXT
9           region       TEXT
10      product_id       TEXT
11        category       TEXT
12    sub_category       TEXT
13    product_name       TEXT
14  product_name.1       TEXT
15      Unit Price    INTEGER
16        quantity    INTEGER
17        discount       REAL
18   shipping_cost       REAL
19  order_priority       TEXT
20           sales    INTEGER
21        expenses       REAL
22        revenue        REAL
23            year    INTEGER

In [16]:
# Q5 — Total revenue
query = """select sum(sales) as total_sales
           from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   total_sales
0     42397613

In [17]:
# Q6 — Total expenses
query = """select sum(expenses) as total_expenses
           from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   total_expenses
0    3.290408e+07

In [18]:
# Q7 — Total quantity sold
query = """select sum(quantity) as total_quantity
           from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   total_quantity
0          178385

In [19]:
# Q8 — Average transaction sales -> NOTE THAT THIS IS NOT ACUTAL AOV
query = """select avg(sales) as avg_transaction_sales
            from ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   avg_transaction_sales
0             826.174305

In [20]:
# Actual Aov
query = """SELECT 
    SUM(sales) / COUNT(DISTINCT order_id) AS average_order_value
FROM ecommerce;"""
pd.read_sql_query(query,ecommerce_database)

   average_order_value
0                 1693

In [21]:
# Q9 — Minimum and maximum sales
min_max_sales = """select min(sales) as minimum_sales,
                            max(sales) as maximum_sales
                    from ecommerce;"""
pd.read_sql_query(min_max_sales, ecommerce_database)

   minimum_sales  maximum_sales
0             19           6398

# 3. WHERE — filtering

In [22]:
# Q10 — Consumer segment only
query = """select *
            from ecommerce
            where segment = 'Consumer'
            limit 10;"""
pd.read_sql_query(query,ecommerce_database)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,product_name.1,Unit Price,quantity,discount,shipping_cost,order_priority,sales,expenses,revenue,year
0,AG-2011-2040,2011-01-01 00:00:00,2011-01-06 00:00:00,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Blue,211,2,0.00,35.46,Medium,422,397.9902,457.46,2011
1,IN-2011-47883,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,High Speed,129,3,0.10,9.72,Medium,387,311.4774,358.02,2011
2,HU-2011-1220,2011-01-01 00:00:00,2011-01-05 00:00:00,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Single Width,128,4,0.00,8.17,High,512,452.5479,520.17,2011
3,CA-2011-1510,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Duo Pack,222,5,0.10,4.70,Medium,1110,873.2190,1003.70,2088
4,IN-2011-79397,2011-01-01 00:00:00,2011-01-08 00:00:00,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,8.5 x 11,299,2,0.10,1.80,Medium,598,469.8000,540.00,2011
5,ID-2011-80230,2011-01-02 00:00:00,2011-01-06 00:00:00,Standard Class,Magdelene Morse,Consumer,Ontario,Canada,Canada,Canada,...,Wireless,378,1,0.00,24.10,Medium,378,349.8270,402.10,2011
6,IN-2011-65159,2011-01-03 00:00:00,2011-01-09 00:00:00,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Laser,400,4,0.40,107.10,Low,1600,928.3770,1067.10,2011
7,IN-2011-33652,2011-01-03 00:00:00,2011-01-07 00:00:00,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Industrial,186,3,0.45,33.75,High,558,296.3655,340.65,2011
8,MX-2011-160234,2011-01-03 00:00:00,2011-01-07 00:00:00,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Adjustable Height,217,1,0.55,21.32,High,217,103.5039,118.97,2011
9,IR-2011-770,2011-01-03 00:00:00,2011-01-07 00:00:00,Standard Class,Dorothy Dickinson,Consumer,England,United Kingdom,EU,North,...,Traditional,296,7,0.00,12.56,Medium,2072,1813.5672,2084.56,2011

In [23]:
# Q11 — Orders with sales greater than 1,000
query = """ select order_id
            from ecommerce
            where (sales > 1000)
            limit 10 ;"""
pd.read_sql_query(query,ecommerce_database)

# or 
# query =  select count(order_id) as orders_sales_greater_than1000
#             from ecommerce
#             where sales > 1000;
# pd.read_sql_query(query,ecommerce_database)

          order_id
0     CA-2011-1510
1    IN-2011-65159
2      IR-2011-770
3   US-2011-136007
4   CA-2011-103800
5  ES-2011-3848439
6    IN-2011-29963
7     AO-2011-4910
8  IT-2011-5134922
9   MX-2011-121202

In [24]:
# Q12 — Orders with discount greater than 30%
query = """select order_id, discount
            from ecommerce
            where (discount > 0.3);"""
pd.read_sql_query(query,ecommerce_database)

              order_id  discount
0      IT-2011-3647632      0.50
1        IN-2011-65159      0.40
2        IN-2011-33652      0.45
3       MX-2011-160234      0.55
4         IR-2011-7690      0.40
...                ...       ...
10364       TU-2014-40      0.32
10365   US-2014-133361      0.40
10366    IN-2014-75736      0.47
10367    IN-2014-65131      0.60
10368   US-2014-139703      0.60

[10369 rows x 2 columns]

In [25]:
# Q13 — Orders from a particular market
query = """select order_id, market
            from ecommerce
            where market = 'EU';"""
pd.read_sql_query(query, ecommerce_database)

             order_id market
0         IR-2011-770     EU
1     ES-2011-5496179     EU
2        MZ-2011-1260     EU
3        LE-2011-9590     EU
4      CA-2011-106054     EU
...               ...    ...
9995     NI-2014-9060     EU
9996    IN-2014-65992     EU
9997     SU-2014-5140     EU
9998   CA-2014-118017     EU
9999   US-2014-158526     EU

[10000 rows x 2 columns]

# GROUP BY

In [26]:
# Q14 — Sales by sub-category
q = """select sub_category, sum(sales) as total_sales
        from ecommerce
        group by sub_category
        order by total_sales desc;"""
pd.read_sql_query(q, ecommerce_database)

   sub_category  total_sales
0       BINDERS      5112028
1       STORAGE      4029065
2           ART      3890898
3         PAPER      3044994
4        CHAIRS      2932199
5        PHONES      2820469
6   FURNISHINGS      2641328
7   ACCESSORIES      2633950
8        LABELS      2216509
9      SUPPLIES      2038223
10    FASTENERS      1991569
11    BOOKCASES      1984836
12    ENVELOPES      1974880
13      COPIERS      1766475
14   APPLIANCES      1422895
15     MACHINES      1160876
16       TABLES       736419

In [27]:
# Q15 — Sales by market
q = """select market, sum(sales) as total_sales
        from ecommerce
        group by market
        order by total_sales desc;"""
pd.read_sql_query(q, ecommerce_database)

           market  total_sales
0            APAC      9826497
1           LATAM      9163638
2              US      9095949
3              EU      8921181
4            EMEA      2708768
5          Africa      2469098
6          Canada       211951
7              EU          531

In [28]:
# Q16 — Sales by segment
q = """select segment, sum(sales) as total_sales
        from ecommerce
        group by segment
        order by total_sales desc;"""
pd.read_sql_query(q, ecommerce_database)

       segment  total_sales
0     Consumer     21934908
1    Corporate     12783301
2  Home Office      7679404

In [29]:
# Q17 — Sales and quantity by category
q = """select category, sum(sales) as total_sales, sum(quantity) as total_quantity
        from ecommerce
        group by category
        order by total_sales desc;"""
pd.read_sql_query(q,ecommerce_database)

          category  total_sales  total_quantity
0  OFFICE SUPPLIES     25721061          108234
1       TECHNOLOGY      8381770           35185
2        FURNITURE      8294782           34966

# Multi-column GROUP BY

In [30]:
# Q18 — Market + category
q = """ SELECT TRIM(market) as market, TRIM(category) as category, SUM(sales) as total_sales
        FROM ecommerce
        GROUP BY TRIM(market), TRIM(category)
        ORDER BY total_sales DESC;
        """
pd.read_sql_query(q,ecommerce_database)

# Which market-category combination generates the highest sales => market = EU, category = OFFICE SUPPLIES, total sales = 5899758

    market         category  total_sales
0       EU  OFFICE SUPPLIES      5899758
1     APAC  OFFICE SUPPLIES      5536310
2       US  OFFICE SUPPLIES      5532128
3    LATAM  OFFICE SUPPLIES      5201940
4     APAC        FURNITURE      2178276
5     APAC       TECHNOLOGY      2111911
6    LATAM        FURNITURE      2110765
7       US        FURNITURE      1903949
8    LATAM       TECHNOLOGY      1850933
9     EMEA  OFFICE SUPPLIES      1741530
10      EU       TECHNOLOGY      1696144
11      US       TECHNOLOGY      1659872
12  Africa  OFFICE SUPPLIES      1657844
13      EU        FURNITURE      1325810
14    EMEA       TECHNOLOGY       544118
15  Africa       TECHNOLOGY       477078
16    EMEA        FURNITURE       423120
17  Africa        FURNITURE       334176
18  Canada  OFFICE SUPPLIES       151551
19  Canada       TECHNOLOGY        41714
20  Canada        FURNITURE        18686

In [31]:
# Q19 — Region + category
q = """select region, category, sum(sales) as total_sales
        from ecommerce
        group by region, category
        order by total_sales desc;"""
pd.read_sql_query(q,ecommerce_database)

            region         category  total_sales
0          Central  OFFICE SUPPLIES      6253497
1            South  OFFICE SUPPLIES      3648755
2            North  OFFICE SUPPLIES      2531563
3          Central       TECHNOLOGY      1910735
4          Central        FURNITURE      1791343
5          Oceania  OFFICE SUPPLIES      1753131
6             West  OFFICE SUPPLIES      1750663
7             EMEA  OFFICE SUPPLIES      1741530
8           Africa  OFFICE SUPPLIES      1657844
9   Southeast Asia  OFFICE SUPPLIES      1626969
10            East  OFFICE SUPPLIES      1593182
11           South        FURNITURE      1211437
12      North Asia  OFFICE SUPPLIES      1164277
13           South       TECHNOLOGY      1120253
14    Central Asia  OFFICE SUPPLIES       991933
15           North       TECHNOLOGY       858735
16       Caribbean  OFFICE SUPPLIES       856166
17           North        FURNITURE       830731
18         Oceania       TECHNOLOGY       675340
19         Oceania        FURNITURE       644915
20            West        FURNITURE       628153
21  Southeast Asia       TECHNOLOGY       610113
22  Southeast Asia        FURNITURE       606613
23            EMEA       TECHNOLOGY       544118
24            West       TECHNOLOGY       541408
25            East        FURNITURE       530014
26      North Asia        FURNITURE       501623
27          Africa       TECHNOLOGY       477078
28            East       TECHNOLOGY       472216
29      North Asia       TECHNOLOGY       425607
30    Central Asia        FURNITURE       425125
31            EMEA        FURNITURE       423120
32    Central Asia       TECHNOLOGY       400851
33       Caribbean        FURNITURE       348846
34          Africa        FURNITURE       334176
35       Caribbean       TECHNOLOGY       303602
36          Canada  OFFICE SUPPLIES       151551
37          Canada       TECHNOLOGY        41714
38          Canada        FURNITURE        18686

# 6. HAVING

## Difference between where and having clause
**WHERE → filters individual rows**
**HAVING → filters groups after GROUP BY**

In [32]:
# Q20 — Customers whose total sales exceed 50,000
q = """select customer_name, sum(sales) as total_sales
        from ecommerce
        group by customer_name
        having (sum(sales) > 50000)
        order by total_sales desc;"""
pd.read_sql_query(q,ecommerce_database)

          customer_name  total_sales
0       Muhammed Yedwab        98959
1           Steven Ward        92507
2       Patrick O'Brill        90998
3       Brosina Hoffman        88393
4          Noel Staavos        86729
..                  ...          ...
459    Dianna Vittorini        50159
460         Chuck Magee        50154
461  Lauren Leatherbury        50129
462         Adrian Hane        50031
463       Aaron Hawkins        50021

[464 rows x 2 columns]

In [33]:
# Q.21 Categories with sales greater than 10 million
q = """select category, sum(sales) as total_sales
        from ecommerce
        group by category
        having sum(sales) >10000000
        order by total_sales desc;"""
pd.read_sql_query(q,ecommerce_database)

          category  total_sales
0  OFFICE SUPPLIES     25721061

# CASE WHEN

In [34]:
#Q. 22 Classify orders by sales
q = """SELECT
    order_id,
    sales,
    CASE
        WHEN sales >= 1000 THEN 'High'
        WHEN sales >= 500 THEN 'Medium'
        ELSE 'Low'
    END AS sales_category
FROM ecommerce
LIMIT 20;"""
pd.read_sql_query(q,ecommerce_database)

           order_id  sales sales_category
0      AG-2011-2040    422            Low
1     IN-2011-47883    387            Low
2      HU-2011-1220    512         Medium
3   IT-2011-3647632    531         Medium
4      CA-2011-1510   1110           High
5     IN-2011-79397    598         Medium
6     ID-2011-80230    378            Low
7      IZ-2011-4680    254            Low
8     IN-2011-65159   1600           High
9   ES-2011-4869686    240            Low
10    IN-2011-33652    558         Medium
11   MX-2011-160234    217            Low
12      IR-2011-770   2072           High
13    ID-2011-12596    309            Low
14     IR-2011-7690    516         Medium
15     TZ-2011-7370    536         Medium
16   MX-2011-111255    152            Low
17   MX-2011-140641    436            Low
18   MX-2011-158771    588         Medium
19  ES-2011-4939443    172            Low

In [35]:
# Q23 — Classify discounts
q = """SELECT
    order_id,
    discount,
    CASE
        WHEN discount >= 0.30 THEN 'High Discount'
        WHEN discount >= 0.10 THEN 'Medium Discount'
        ELSE 'Low Discount'
    END AS discount_category
FROM ecommerce
LIMIT 20;"""
pd.read_sql_query(q,ecommerce_database)

           order_id  discount discount_category
0      AG-2011-2040      0.00      Low Discount
1     IN-2011-47883      0.10   Medium Discount
2      HU-2011-1220      0.00      Low Discount
3   IT-2011-3647632      0.50     High Discount
4      CA-2011-1510      0.10   Medium Discount
5     IN-2011-79397      0.10   Medium Discount
6     ID-2011-80230      0.00      Low Discount
7      IZ-2011-4680      0.10   Medium Discount
8     IN-2011-65159      0.40     High Discount
9   ES-2011-4869686      0.00      Low Discount
10    IN-2011-33652      0.45     High Discount
11   MX-2011-160234      0.55     High Discount
12      IR-2011-770      0.00      Low Discount
13    ID-2011-12596      0.00      Low Discount
14     IR-2011-7690      0.40     High Discount
15     TZ-2011-7370      0.00      Low Discount
16   MX-2011-111255      0.00      Low Discount
17   MX-2011-140641      0.40     High Discount
18   MX-2011-158771      0.40     High Discount
19  ES-2011-4939443      0.47     High Discount

In [36]:
# Q24 — Sales performance by market
q = """
    SELECT 
        TRIM(market) AS market,
        COUNT(DISTINCT order_id) AS total_orders,
        SUM(quantity) AS total_quantity,
        SUM(sales) AS total_sales,
        AVG(sales) AS avg_transaction_sales
    FROM ecommerce
    GROUP BY TRIM(market)
    ORDER BY total_sales DESC;
"""
pd.read_sql_query(q,ecommerce_database)

   market  total_orders  total_quantity  total_sales  avg_transaction_sales
0    APAC          8919           41233      9826497             892.830910
1   LATAM          8441           38563      9163638             889.328222
2      US          8231           37892      9095949             909.594900
3      EU          8187           37776      8921712             892.081992
4    EMEA          4506           11521      2708768             538.201470
5  Africa          4125           10567      2469098             537.929847
6  Canada           374             833       211951             551.955729

In [37]:
q = """SELECT
    typeof(sales) AS stored_type,
    COUNT(*) AS row_count
FROM ecommerce
GROUP BY typeof(sales);"""
pd.read_sql_query(q,ecommerce_database)

  stored_type  row_count
0     integer      51318

In [38]:
# 1. Find the top 10 states by sales
q = """select state, sum(sales) as total_sales
        from ecommerce
        group by state
        order by total_sales desc
        limit 10;"""
pd.read_sql_query(q,ecommerce_database)

                    state  total_sales
0              California      1711284
1                 England      1260070
2                New York       914348
3           Ile-de-France       871744
4                   Texas       865556
5         New South Wales       688438
6  North Rhine-Westphalia       618037
7              Queensland       607312
8            San Salvador       522336
9        National Capital       520120

In [39]:
# Q.2 Find customers whose total sales exceed ₹50,000
q = """select customer_name, sum(sales) as total_sales
        from ecommerce
        group by customer_name
        having (sum(sales) > 50000)
        order by total_sales desc;"""
pd.read_sql_query(q,ecommerce_database)

          customer_name  total_sales
0       Muhammed Yedwab        98959
1           Steven Ward        92507
2       Patrick O'Brill        90998
3       Brosina Hoffman        88393
4          Noel Staavos        86729
..                  ...          ...
459    Dianna Vittorini        50159
460         Chuck Magee        50154
461  Lauren Leatherbury        50129
462         Adrian Hane        50031
463       Aaron Hawkins        50021

[464 rows x 2 columns]

In [40]:
# Q.3 Calculate sales by year
# Use strftime('%Y', order_date) if the dates are stored as SQLite dates.

q = """
SELECT 
    strftime('%Y', order_date) AS sales_year,
    SUM(sales) AS total_sales
FROM 
    ecommerce
GROUP BY 
    sales_year
ORDER BY 
    total_sales DESC;
"""


pd.read_sql_query(q, ecommerce_database)

  sales_year  total_sales
0       2014     14458562
1       2013     11454286
2       2012      9018733
3       2011      7466032

In [41]:
# 4. Compare sales and expenses by market
q = """select  trim(market), sum(sales) as total_sales, sum(expenses) as total_expenses
        from ecommerce
        group by trim(market);
        """
pd.read_sql_query(q, ecommerce_database)

  trim(market)  total_sales  total_expenses
0         APAC      9826497    7.613304e+06
1       Africa      2469098    1.892035e+06
2       Canada       211951    1.908403e+05
3         EMEA      2708768    1.981372e+06
4           EU      8921712    7.232677e+06
5        LATAM      9163638    7.111588e+06
6           US      9095949    6.882262e+06

In [42]:
# 5. Count orders in each shipping mode
q= """select ship_mode , count(order_id) as total_orders
    from ecommerce
    group by ship_mode;"""  # this query does not count null 

# OR 
# q = """SELECT 
#     ship_mode, 
#     COUNT(*) AS total_orders
# FROM 
#     ecommerce
# GROUP BY 
#     ship_mode;
# """
pd.read_sql_query(q,ecommerce_database)

        ship_mode  total_orders
0     First Class          7505
1        Same Day          2705
2    Second Class         10310
3  Standard Class         30777

In [43]:
q= """select ship_mode , count(order_id) as total_orders
    from ecommerce
    group by ship_mode;"""

pd.read_sql_query(q,ecommerce_database)

        ship_mode  total_orders
0     First Class          7505
1        Same Day          2705
2    Second Class         10310
3  Standard Class         30777